name: Unit tests
on: [push]

env:
  node-version: 16.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Main checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      # node install
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Unit tests
      - name: Unit tests
        run: yarn test:ci
